Install-WindowsFeature -Name Web-Server -IncludeAllSubFeature -IncludeManagementTools
dism /online /Enable-Feature /FeatureName:IIS-WebServerRole
dism /online /Enable-Feature /FeatureName:IIS-WebServer
dism /online /Enable-Feature /FeatureName:IIS-CommonHttpFeatures
dism /online /Enable-Feature /FeatureName:IIS-HttpErrors
dism /online /Enable-Feature /FeatureName:IIS-HttpRedirect
dism /online /Enable-Feature /FeatureName:IIS-ApplicationDevelopment
dism /online /Enable-Feature /FeatureName:IIS-Security
dism /online /Enable-Feature /FeatureName:IIS-RequestFiltering
dism /online /Enable-Feature /FeatureName:IIS-NetFxExtensibility
dism /online /Enable-Feature /FeatureName:IIS-WebServerManagementTools
dism /online /Enable-Feature /FeatureName:IIS-ManagementScriptingTools
dism /online /Enable-Feature /FeatureName:IIS-ISAPIExtensions
dism /online /Enable-Feature /FeatureName:IIS-ISAPIFilter
dism /online /Enable-Feature /FeatureName:IIS-StaticContent
dism /online /Enable-Feature /FeatureName:IIS-DefaultDocument
dism /online /Enable-Feature /FeatureName:IIS-ASPNET
dism /online /Enable-Feature /FeatureName:IIS-ASP
dism /online /Enable-Feature /FeatureName:IIS-ManagementConsole
dism /online /Enable-Feature /FeatureName:IIS-ManagementService
